version: '3'

services: 
    demo:
        build: .
        container_name: demo
        ports:
            - "80:19000"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
